### ISSUE TITLE
koop serve fails when path has spaces

### ISSUE THREAD

**Issue by tannerjt** [koopjs/koop-cli#42]
`koop serve` fails when directory has spaces in name.   IE `/my project/koop`.

```
Error: Cannot find module '/my '
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by haoliangyu** [comment]
@tannerjt A new version (v0.6.1) is published to address this bug. Can you verify?

**Comment by tannerjt** [comment]
Thanks @haoliangyu.  I can confirm both `koop serve` and `koop serve --watch` both work and your solution for quoting the math for linux/mac is a good solution.
