### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/node_modules/latest-version/index.js

### ISSUE THREAD

**Issue by mlewis22** [koopjs/koop-cli#89]
After installing Koopjs CLI as per instructions. 'koop' command failed with error below.

I am using node version -- v16.14.2, NPM: 8.5.0

I have tried downgrading node-fetch to 2.6.1. This had no impact. 

I was looking for an answer that avoided re writing the imports. #

```
$ koop
/opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/src/utils/add-plugin/add-npm-plugin.js:3
const latestVersion = require('latest-version')
                      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/node_modules/latest-version/index.js from /opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/src/utils/add-plugin/add-npm-plugin.js not supported.
Instead change the require of index.js in /opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/src/utils/add-plugin/add-npm-plugin.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/src/utils/add-plugin/add-npm-plugin.js:3:23)
    at Object.<anonymous> (/opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/src/utils/add-plugin/index.js:4:22)
    at Object.<anonymous> (/opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/src/cli/commands/add.js:1:19)
    at /opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/node_modules/require-directory/index.js:76:17
    at Array.forEach (<anonymous>)
    at Object.requireDirectory (/opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/node_modules/require-directory/index.js:59:24)
    at M.addDirectory (/opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/node_modules/yargs/build/index.cjs:1:5492)
    at Xt.commandDir (/opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/node_modules/yargs/build/index.cjs:1:32877)
    at Object.<anonymous> (/opt/nodejs/16.14.2/lib/node_modules/@koopjs/cli/src/cli/index.js:9:4) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by haoliangyu** [comment]
The fix is released at v1.1.4.
